
String index_html_get =

"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"    <meta charset=\"UTF-8\">"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"    <title>Camera Slider Control</title>"
"    <style>"
"        body {"
"            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;"
"            max-width: 400px;"
"            margin: 50px auto;"
"            padding: 20px;"
"            background: #0a0a0a;"
"        }"
"        "
"        .container {"
"            background: linear-gradient(145deg, #1e1e1e, #2a2a2a);"
"            padding: 40px;"
"            border-radius: 24px;"
"            box-shadow: 0 20px 60px rgba(0,0,0,0.8), 0 0 1px rgba(255,255,255,0.1) inset;"
"            border: 1px solid rgba(255,255,255,0.05);"
"        }"
"        "
"        h1 {"
"            margin-top: 0;"
"            margin-bottom: 30px;"
"            color: #ffffff;"
"            font-weight: 600;"
"            font-size: 28px;"
"            letter-spacing: -0.5px;"
"        }"
"        "
"        .form-group {"
"            margin-bottom: 20px;"
"        }"
"        "
"        label {"
"            display: block;"
"            margin-bottom: 8px;"
"            color: #a0a0a0;"
"            font-weight: 500;"
"            font-size: 14px;"
"            letter-spacing: 0.3px;"
"        }"
"        "
"        input[type=\"number\"],"
"        select {"
"            width: 100%;"
"            padding: 12px 16px;"
"            border: 1px solid rgba(255,255,255,0.1);"
"            border-radius: 12px;"
"            font-size: 16px;"
"            box-sizing: border-box;"
"            background: rgba(0,0,0,0.3);"
"            color: #ffffff;"
"            transition: all 0.3s ease;"
"        }"
"        "
"        input[type=\"number\"]:focus,"
"        select:focus {"
"            outline: none;"
"            border-color: #007bff;"
"            background: rgba(0,0,0,0.4);"
"        }"
"        "
"        input[type=\"range\"] {"
"            width: 100%;"
"            margin-bottom: 10px;"
"            height: 6px;"
"            background: rgba(255,255,255,0.1);"
"            border-radius: 10px;"
"            outline: none;"
"            -webkit-appearance: none;"
"        }"
"        "
"        input[type=\"range\"]::-webkit-slider-thumb {"
"            -webkit-appearance: none;"
"            appearance: none;"
"            width: 20px;"
"            height: 20px;"
"            background: #007bff;"
"            border-radius: 50%;"
"            cursor: pointer;"
"            box-shadow: 0 2px 8px rgba(0,123,255,0.4);"
"        }"
"        "
"        input[type=\"range\"]::-moz-range-thumb {"
"            width: 20px;"
"            height: 20px;"
"            background: #007bff;"
"            border-radius: 50%;"
"            cursor: pointer;"
"            border: none;"
"            box-shadow: 0 2px 8px rgba(0,123,255,0.4);"
"        }"
"        "
"        input[type=\"number\"] {"
"            width: 120px;"
"        }"
"        "
"        button {"
"            width: 100%;"
"            padding: 14px;"
"            background: linear-gradient(135deg, #007bff, #0056b3);"
"            color: white;"
"            border: none;"
"            border-radius: 12px;"
"            font-size: 16px;"
"            cursor: pointer;"
"            font-weight: 600;"
"            transition: all 0.3s ease;"
"            box-shadow: 0 4px 15px rgba(0,123,255,0.3);"
"        }"
"        "
"        button:hover {"
"            transform: translateY(-2px);"
"            box-shadow: 0 6px 20px rgba(0,123,255,0.4);"
"        }"
"        "
"        button:active {"
"            transform: translateY(0);"
"        }"
"    </style>"
"</head>"
"<body>"
"    <div class=\"container\">"
"        <h1>Camera Slider</h1>"
"        <form action=\"\" method=\"POST\">"
"            <div class=\"form-group\">"
"                <label for=\"speed\">Speed (mm/min)</label>"
"                <input type=\"range\" id=\"speed\" name=\"speed\" min=\"1\" max=\"1000\" value=\"100\" oninput=\"document.getElementById('speedValue').value = this.value\">"
"                <input type=\"number\" id=\"speedValue\" name=\"speedValue\" min=\"1\" max=\"1000\" value=\"100\" oninput=\"document.getElementById('speed').value = this.value\">"
"            </div>"
"            "
"            <div class=\"form-group\">"
"                <label for=\"direction\">Direction</label>"
"                <select id=\"direction\" name=\"direction\" required>"
"                    <option value=\"left\">Left</option>"
"                    <option value=\"right\">Right</option>"
"                </select>"
"            </div>"
"            "
"            <div class=\"form-group\">"
"                <label for=\"duration\">Duration (seconds)</label>"
"                <input type=\"number\" id=\"duration\" name=\"duration\" min=\"1\" max=\"300\" value=\"5\" required>"
"            </div>"
"            "
"            <button type=\"submit\">Start Slider</button>"
"        </form>"
"    </div>"
"</body>"
"</html>";

